library(shiny)
library(shinyjs)
library(shinyalert)

library(tm)
library(stringr)
library(quanteda)
library(DT)
library(lexiconPT)
library(tidyverse)
library(tidytext)
library(magrittr)
library(reshape2)

library(ggplot2) 
library(ggExtra)
library(wordcloud2)
library(visNetwork)